### ISSUE TITLE
Add an export function to get the detailed orders

### ISSUE THREAD

**Issue by AnomalRoil** [Polyjapan/ji-shop#8]
It would be useful for tracking the sales to be able to export a CSV with the following:
`ordered_products.` : 
- productId 
- orderId   
- paidPrice 

with an INNER JOIN ON `ordered_products.orderId = orders.id` and the following fields from `orders.` :
- enterDate          
- id               
- ticketsPrice     
- totalPrice       
- paymentConfirmed

**Comment by zyuiop** [comment]
Fixed by c7cef13
